In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv("/content/train_LR (1).csv")
df1.head()

Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0     2   729    66  22000.0            -10              5.75  6.29   
1     1   786    60  37000.0            -10              4.09  4.09   
2     1   742    60  25000.0            -10              3.99  3.99   
3     1   631    60  25000.0            -10              4.59  4.49   
4     4   656    72  27300.0            -10              5.35  7.99   

   Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_U  Accept  
0      1.1625            1           0           0           1       1  
1      1.1400            2           1           0           0       0  
2      1.1163            3           1           0           0       0  
3      1.6150            1           1           0           0       0  
4      1.1200            1           0           0           1       1

In [ ]:
df2 = pd.read_csv("/content/test_LR (1).csv")
df2.head()

Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0     2   725    72  30500.0              5              6.09  4.99   
1     1   739    60  25995.0            -10              4.79  4.79   
2     2   715    48  30000.0              5              5.19  4.79   
3     1   742    60  45000.0            -10              4.59  4.59   
4     4   649    60  27900.0            -10              4.49  6.99   

   Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_U  Accept  
0      1.1200            2           0           1           0       0  
1      1.9590            2           0           0           1       0  
2      1.1200            2           0           1           0       0  
3      1.5788            3           1           0           0       0  
4      1.3206            3           1           0           0       1

### Q1

How many observations are available in the training data? Hint: Enter your answer as an integer.

In [ ]:
df1.shape

(109244, 13)

### Q2
How many observations are available in the test data? Hint: Enter your answer as an integer.

In [ ]:
df2.shape

(36415, 13)

In [ ]:
df1.describe

<bound method NDFrame.describe of         Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0          2   729    66  22000.0            -10              5.75  6.29   
1          1   786    60  37000.0            -10              4.09  4.09   
2          1   742    60  25000.0            -10              3.99  3.99   
3          1   631    60  25000.0            -10              4.59  4.49   
4          4   656    72  27300.0            -10              5.35  7.99   
...      ...   ...   ...      ...            ...               ...   ...   
109239     1   786    36  35000.0            -10              3.79  3.79   
109240     2   692    36  11900.0              6              4.75  5.03   
109241     1   800    60  26955.0            -10              5.49  5.24   
109242     1   746    48  33000.0            -10              4.99  4.44   
109243     3   710    48  15000.0            -10              5.75  5.98   

        Cost_Funds  Partner Bin  Car_Type_N  Car_Type

In [ ]:
df2.describe

<bound method NDFrame.describe of        Tier  FICO  Term   Amount  Previous_Rate  Competition_rate  Rate  \
0         2   725    72  30500.0              5              6.09  4.99   
1         1   739    60  25995.0            -10              4.79  4.79   
2         2   715    48  30000.0              5              5.19  4.79   
3         1   742    60  45000.0            -10              4.59  4.59   
4         4   649    60  27900.0            -10              4.49  6.99   
...     ...   ...   ...      ...            ...               ...   ...   
36410     1   739    36  11400.0              9              4.75  4.75   
36411     2   704    72  15800.0             12              6.09  6.94   
36412     1   761    60  36000.0            -10              4.89  3.89   
36413     1   752    48  12093.0             10              5.29  5.25   
36414     3   682    60  23000.0            -10              4.49  5.15   

       Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_

In [ ]:
df1.isnull().sum()

Tier                0
FICO                0
Term                0
Amount              0
Previous_Rate       0
Competition_rate    0
Rate                0
Cost_Funds          0
Partner Bin         0
Car_Type_N          0
Car_Type_R          0
Car_Type_U          0
Accept              0
dtype: int64

In [ ]:
df2.isnull().sum()

Tier                0
FICO                0
Term                0
Amount              0
Previous_Rate       0
Competition_rate    0
Rate                0
Cost_Funds          0
Partner Bin         0
Car_Type_N          0
Car_Type_R          0
Car_Type_U          0
Accept              0
dtype: int64

In [ ]:
df1.dtypes

Tier                  int64
FICO                  int64
Term                  int64
Amount              float64
Previous_Rate         int64
Competition_rate    float64
Rate                float64
Cost_Funds          float64
Partner Bin           int64
Car_Type_N            int64
Car_Type_R            int64
Car_Type_U            int64
Accept                int64
dtype: object

In [ ]:
df2.dtypes

Tier                  int64
FICO                  int64
Term                  int64
Amount              float64
Previous_Rate         int64
Competition_rate    float64
Rate                float64
Cost_Funds          float64
Partner Bin           int64
Car_Type_N            int64
Car_Type_R            int64
Car_Type_U            int64
Accept                int64
dtype: object

### Q3 and Q4

**Q3** : What is the proportion of customers who have not accepted the loan in the training dataset?
Hint: Mention your answer in terms of percentage.
If your answer is 70.51%, enter 70.51

**Q4** : What is the proportion of customers who have accepted the loan in the training dataset?
Hint: Mention your answer in terms of percentage. If your answer is 70.51%, enter 70.51

In [ ]:
df1['Accept'].value_counts(normalize = True)

0    0.780436
1    0.219564
Name: Accept, dtype: float64

### Q5 and Q6

**Q5**: What is the proportion of customers who have not accepted the loan in the test dataset?
Hint: Mention your answer in terms of percentage. If your answer is 70.51%, enter 70.51

**Q6**:
What is the proportion of customers who have accepted the loan in the test dataset?
Hint: Mention your answer in terms of percentage. If your answer is 70.51%, enter 70.51


In [ ]:
df2['Accept'].value_counts(normalize = True)

0    0.778525
1    0.221475
Name: Accept, dtype: float64

In [ ]:
df1.columns

Index(['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U', 'Accept'],
      dtype='object')

In [ ]:
features = ['Tier','FICO','Term','Amount','Previous_Rate','Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U']

In [ ]:
target = ['Accept']

In [ ]:
X_train = df1[features]
y_train = df1[target]
print(X_train.shape,y_train.shape)

(109244, 12) (109244, 1)


In [ ]:
X_test = df2[features]
y_test = df2[target]

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
print(X_test.shape,y_test.shape)

(36415, 12) (36415, 1)


In [ ]:
logreg = LogisticRegression(random_state=17)

logreg.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=17)

In [ ]:
y_pred_train = logreg.predict(X_train)
y_pred_test = logreg.predict(X_test)

In [ ]:
print(y_pred_train.shape)
print(y_pred_test.shape)

(109244,)
(36415,)


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
train_cfm = confusion_matrix(y_train,y_pred_train)
test_cfm = confusion_matrix(y_test,y_pred_test)

train_cfm , test_cfm

(array([[80324,  4934],
        [16342,  7644]]),
 array([[26624,  1726],
        [ 5550,  2515]]))

In [ ]:
import numpy as np

96666

In [ ]:
TN_train , FP_train , FN_train , TP_train = train_cfm[0][0] , train_cfm[0][1] , train_cfm[1][0] , train_cfm[1][1]
TN_test , FP_test , FN_test , TP_test = test_cfm[0][0] , test_cfm[0][1] , test_cfm[1][0] , test_cfm[1][1]


Accuracy_train = (TN_train + TP_train) / (TN_train + FP_train + FN_train + TP_train)
Accuracy_test = (TN_test + TP_test) / (TN_test + FP_test + FN_test + TP_test)

Precision0_train = TN_train / (TN_train + FN_train)
Precision1_train = TP_train / (TP_train + FP_train)
Precision0_test = TN_test / (TN_test + FN_test)
Precision1_test = TP_test / (TP_test + FP_test)

Recall0_train = TN_train/(TN_train + FP_train)
Recall1_train = TP_train/(TP_train + FN_train)
Recall0_test = TN_test/(TN_test + FP_test)
Recall1_test = TP_test/(TP_test + FN_test)

[ 1.03178587  5.38293966 11.50811094] 0.8309436616804253 0.3186859001083966
[ 1.02783069  5.25027027 11.5860835 ] 0.59302051402971 0.31184128952262863
0.6077277786611543 0.59302051402971


### Q7

Fit the model on the train data (use LogisticRegression from sklearn.linear_model and random state=17) and make predictions on the train data, and answer questions (7 to 9).

What is the training accuracy? If your answer is 70.51%, enter 70.5.
Hint: Compare the predictions of y_train and y_pred_train. If your answer is 70.51%, enter 70.51



In [ ]:
Accuracy_train = (TN_train + TP_train) / (TN_train + FP_train + FN_train + TP_train)

Accuracy_train

0.8052433085569917

### Q8
What is the training data precision of your model if the aim is to find customers who will not
accept the loan?
Hint: Compare the predictions of y_train and y_pred_train. Mention your answer in terms of percentage. If your answer is 70.51%, enter 70.51


In [ ]:
Precision0_train = TN_train / (TN_train + FN_train)

Precision0_train

0.8309436616804253

### Q9
What is the training data recall of your model if the aim is to find customers who will accept the loan?
Hint: enter your answer in terms of percentage, If your answer is 70.51%, enter 70.51


In [ ]:
Recall1_train = TP_train/(TP_train + FN_train)

Recall1_train

0.3186859001083966

### Q10

After training your model on the train data, make predictions on the test data, and answer questions 10 to 14. From the confusion matrix, identify the number of predictions that have a type 1 error (false positive).
Hint: Use confusion_matrix(y_test, y_pred_test).ravel() and enter your answer as an integer


In [ ]:
FP_test

1726

### Q11

In the test data confusion matrix, identify the number of predictions that have a type 2 error (false negative).
Hint: Use confusion_matrix(y_test, y_pred_test).ravel() and enter your answer as an integer.


In [ ]:
FN_test

5550

### Q12
What is the accuracy of the model in the test data? Mention your answer in terms of percentage and round off the answers to two decimals.
Hint: If your answer is 70.51%, enter 70.51


In [ ]:
Accuracy_test = (TN_test + TP_test) / (TN_test + FP_test + FN_test + TP_test)

Accuracy_test

0.8001922284772759

### Q13
What is the precision of your model in the test data if the aim is to find customers who will accept the loan?
Hint: Mention your answer in terms of percentage and round off the answers to two decimals. If your answer is 70.51%, enter 70.51


In [ ]:
Precision1_test = TP_test / (TP_test + FP_test)

Precision1_test

0.59302051402971

### Q14

What is the recall of your model in the test data if the aim is to find customers who will accept the loan?
Mention your answer in terms of percentage and round off the answers to two decimals. If your answer is 70.51%, enter 70.51


In [ ]:
Recall1_test = TP_test/(TP_test + FN_test)

Recall1_test

0.31184128952262863

In [ ]:
print(classification_report(y_train,y_pred_train))
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.83      0.94      0.88     85258
           1       0.61      0.32      0.42     23986

    accuracy                           0.81    109244
   macro avg       0.72      0.63      0.65    109244
weighted avg       0.78      0.81      0.78    109244

              precision    recall  f1-score   support

           0       0.83      0.94      0.88     28350
           1       0.59      0.31      0.41      8065

    accuracy                           0.80     36415
   macro avg       0.71      0.63      0.64     36415
weighted avg       0.78      0.80      0.78     36415



In [ ]:
y_pred_prob = logreg.predict_proba(X_test)[:,1]

In [ ]:
y_pred_prob

array([0.41136038, 0.31681103, 0.17099025, ..., 0.1027908 , 0.56960924,
       0.15682777])

In [ ]:
df3 = pd.DataFrame()

In [ ]:
df3['test'] = y_test

In [ ]:
df3['pred'] = y_pred

In [ ]:
df3['pred_proba'] = y_pred_prob

In [ ]:
df3.head(20)

test  pred  pred_proba
0      0     0    0.411360
1      0     0    0.316811
2      0     0    0.170990
3      0     0    0.027734
4      1     0    0.029692
5      0     0    0.430316
6      0     0    0.129829
7      0     0    0.097641
8      1     0    0.455886
9      0     0    0.136211
10     0     0    0.133959
11     0     0    0.212989
12     0     0    0.192136
13     0     0    0.239110
14     1     1    0.581316
15     0     0    0.025912
16     0     1    0.663350
17     0     0    0.142146
18     0     0    0.020397
19     0     0    0.101337