Step 1: Download the dataset using following link: (https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing)

Step 2: Import the data in google colab using pd.read_csv().

Step 3: Seperate features and target data in seperate variable X and Y.

Step 4: Convert dataframe X and series y into array and save it in variable X_array,y_array.

Step 5: Split the dataset using train_test_split. (Keep parameter test_size=0.3 and random_state=10).

Step 6: Reshape the dataset in such a way that each entry of data has 90 samples.

Step 7: Use SGD regressor as an estimator and partial_fit to fit the dataset on the model. (Set random_state=10)

Step 8: Calculate different evaluation metrics value like mean_square_error, R2_score.

Use the training set for fitting the model and use the test data to make the predictions.

Note: No need to scale the data. It's already scaled.

Answer the below questions.

In [1]:
import pandas as pd
import numpy as np

/tmp/ipykernel_274240/2162656668.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv("data_for_large_scale.csv")

In [3]:
X = df.drop(columns = ["Target"])
y = df["Target"]

In [4]:
X_array = X.to_numpy()
y_array = y.to_numpy()

In [5]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train ,y_test = train_test_split(X_array , y_array , test_size=0.3 , random_state=10)

In [6]:
from sklearn.linear_model import SGDRegressor

clf = SGDRegressor(random_state=10)

In [7]:
index = 90

while index <= X_train.shape[0]:
    X = X_train[index - 90 : index]
    y = y_train[index - 90 : index]

    clf.partial_fit(X,y)
    index += 90

### 1) How many fetaures are there in the dataset?

In [8]:
X_train.shape[1]

10

### 2) What is the value of intercept you got after training the model using SGDRegressor?(select the closest answer)

In [9]:
clf.intercept_

array([-0.0054532])

### 3) What is the value of cofficient corresponding to "feature-3"you got after trainig the model using SGDRegressor? (select the closest answer)

In [10]:
clf.coef_[2]

81.2376286796651

### 4) What is the value of R2 score for test data


In [11]:
from sklearn.metrics import r2_score

r2_score(y_test , clf.predict(X_test))

0.9999919793766233

### 5) What is the value of cofficient corresponding to "feature-5" after 5th iteration.

In [12]:
from sklearn.linear_model import SGDRegressor

clf = SGDRegressor(random_state=10)

index = 90
iteration = 1

while index <= X_train.shape[0]:
    X = X_train[index - 90 : index]
    y = y_train[index - 90 : index]

    clf.partial_fit(X,y)
    index += 90
    iteration += 1

    if iteration == 5:
        print(clf.coef_[4])

52.09758505423832


## Common Data for 6 to 8 questions

This dataset was constructed by adding elevation information to a 2D road network in North Jutland, Denmark (covering a region of 185 x 135 km^2). Elevation values where extracted from a publicly available massive Laser Scan Point Cloud for Denmark. This 3D road network was eventually used for benchmarking various fuel and CO2 estimation algorithms. This dataset can be used by any applications that require to know very accurate elevation information of a road network to perform more accurate routing for eco-routing, cyclist routes etc. For the data mining and machine learning community, this dataset can be used as 'ground-truth' validation in spatial mining techniques and satellite image processing. It has no class labels,

Use this dataset to guess some missing elevation information for some points on the road.

Column names:

OSM_ID: OpenStreetMap ID for each road segment or edge in the graph.

LONGITUDE: Web Mercaptor (Google format) longitude

LATITUDE: Web Mercaptor (Google format) latitude

ALTITUDE: Height in meters.

Load the dataset from link("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"). Set parameter chunk size=20000 and iterator =True in pd.read_csv().

NOTE: The above file doesn't have column names

Scale your whole dataset first with standard scalar using partial_fit method. Then use SGDRegressor(random state=10) on the dataset and answer the following.

In [13]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", chunksize=20_000 , iterator=True , header=None).read()

KeyboardInterrupt: 

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df2_array = scaler.fit_transform(df2)

### 6) Check how many total samples are there in the dataset?

In [ ]:
df2_array.shape

### 7) What is the value of intercept after 7th iteration. (select the closest option).

In [20]:
chunksize = 20000
iteration = 1
dataset_size = 0
sgdr = SGDRegressor(random_state=10)

from sklearn.preprocessing import StandardScaler
stdslr = StandardScaler()
for train_df in pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt'
                            , chunksize=chunksize,iterator=True):
    X_train = train_df.iloc[:,1:-1]
    y_train = train_df.iloc[:,-1]
    
    if iteration == 1:
        X_train = stdslr.fit_transform(X_train)
    else :
        X_train = stdslr.transform(X_train)
    
    sgdr.partial_fit(X_train, y_train)

    if iteration == 7:
        intercept_iteration_7 = sgdr.intercept_
        coeficient_iteration_7_longituge = sgdr.coef_

    dataset_size += train_df.shape[0]
    iteration+=1
intercept_iteration_7

array([21.19070618])

### 8) What is the value of the coefficient corresponding to the longitude feature after the 7th iteration? (select the closest option).

In [21]:
coeficient_iteration_7_longituge

array([ 3.21593785, -4.60791431])

## Common Data for 9 to 11 questions 
Load Iris datset on Colab and use KNN classifier to build the model Using following steps.

Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10

Step 2: Use Normalizer() as a scaling function to scale the data.

Step 3: Use KNeighborsClassifier(K) as an estimator to predict the output.

In [68]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True , as_frame=True)

In [69]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train ,y_test = train_test_split(X,y , test_size=0.2 , random_state=10)

In [70]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### 9) Which of the following K value gives the best accuracy on test set.



In [80]:
print(KNeighborsClassifier(n_neighbors=2).fit(X_train,y_train).score(X_test,y_test))
print(KNeighborsClassifier(n_neighbors=3).fit(X_train,y_train).score(X_test,y_test))
print(KNeighborsClassifier(n_neighbors=4).fit(X_train,y_train).score(X_test,y_test))

0.9666666666666667
0.9666666666666667
0.9666666666666667


### 10) What is the accuracy for k=3?

In [81]:
print(KNeighborsClassifier(n_neighbors=3).fit(X_train,y_train).score(X_test,y_test))

0.9666666666666667


### 11) Compute wieghted F1 score value for k=3.(Keep parameter average='weighted')


In [84]:
from sklearn.metrics import f1_score 

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train,y_train)

f1_score(y_test , clf.predict(X_test) , average='weighted')

0.9671111111111111